server:
  port: 10086
  context-path: /demo
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
  messages:
    basename: i18n/Messages,i18n/Pages
  mail:
    host: smtp.qq.com:465
    username: 1499296575@qq.com
    password: Mlh223319
    properties:
       mail.smtp.auth: true
       mail.smtp.starttls.enable: true
       mail.smtp.starttls.required: true
  jms:
    pub-sub-domain: true   # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
  activemq:
    user: root    # 连接用户名
    password: 123456   # 连接密码
    broker-url: tcp://127.0.0.1:61616 # 消息组件的连接主机信息
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/user           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                              # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
mybatis:
  mapperLocations: classpath:com/zr/demo/mapper/*.xml
  typeAliasesPackage: com.zr.demo.model
management:
  security:
    enabled: false # 现在关闭系统的安全配置